apiVersion: v1
kind: ConfigMap
metadata:
 name: time-slicing-config
 namespace: nvidia-gpu-operator
data:
 NVIDIA-4060-PCIE-8GB: |-
   version: v1
   sharing:
     timeSlicing:
       resources:
         - name: nvidia.com/gpu
           replicas: 4
